# fly.toml app configuration file generated for mi-primer-cicd-completo-alejandra-ancient-cloud-3148 on 2024-09-30T17:42:45+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mi-primer-cicd-completo-alejandra-ancient-cloud-3148'
primary_region = 'mad'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
